Remove hosts file, add internal cert

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -7,11 +7,23 @@ variables:
 
 build_ci_image:
   stage: infrastructure
+  before_script:
+    - |
+      if [ -f "$INFRA_CA" ]; then
+        mv "$INTERNAL_CA" internal.crt
+      elif [ -n "$INTERNAL_CA" ]; then
+        echo "$INTERNAL_CA" > internal.crt
+      else
+        echo "ERROR: Required variable INFRA_CA is not defined"
+        exit 1
+      fi
   script:
     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
     - docker build --build-arg GO_PROXY_HOST="${GO_PROXY_HOST}" --build-arg GO_PROXY_IP="${GO_PROXY_IP}" -t "$IMAGE_TAG_LATEST" -t "$IMAGE_TAG_COMMIT" .
     - docker push "$IMAGE_TAG_LATEST"
     - docker push "$IMAGE_TAG_COMMIT"
+  after_script:
+    - rm -f internal.crt
   only:
     - master
   tags:
